# Generated by Django 4.1 on 2022-08-16 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crop_predictor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weatherdata",
            name="date",
        ),
    ]
