# Generated by Django 4.1 on 2022-08-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_predictor", "0002_remove_weatherdata_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="date",
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
