# Generated by Django 4.1 on 2022-08-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_predictor", "0003_weatherdata_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="weather_station",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="weatherdata",
            name="date",
            field=models.IntegerField(),
        ),
    ]
