# Generated by Django 4.1 on 2022-08-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_predictor", "0004_weatherdata_weather_station_alter_weatherdata_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatisticsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weather_station", models.CharField(max_length=255)),
                ("year", models.IntegerField()),
                ("max_temp", models.IntegerField()),
                ("min_temp", models.IntegerField()),
                ("precipitation", models.IntegerField()),
            ],
        ),
    ]
