# Generated by Django 4.1 on 2022-08-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_predictor", "0005_statisticsdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statisticsdata",
            name="max_temp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="statisticsdata",
            name="min_temp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="statisticsdata",
            name="precipitation",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
