# Generated by Django 4.1 on 2022-08-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crop_predictor", "0006_alter_statisticsdata_max_temp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statisticsdata",
            name="max_temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="statisticsdata",
            name="min_temp",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="statisticsdata",
            name="precipitation",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
